@startuml

interface demo.uml.classes.Future {
	{method}  {abstract} +cancel ( paramboolean1 : boolean ) : boolean
	{method}  {abstract} +get () : Object
	{method}  {abstract} +get ( paramlong1 : long , paramTimeUnit2 : java.util.concurrent.TimeUnit ) : Object
	{method}  {abstract} +isCancelled () : boolean
	{method}  {abstract} +isDone () : boolean
}


class demo.uml.classes.FutureTask {
	{method} +cancel ( paramboolean1 : boolean ) : boolean
	{method} +get () : Object
	{method} +get ( paramlong1 : long , paramTimeUnit2 : java.util.concurrent.TimeUnit ) : Object
	{method} +isDone () : boolean
	{method} +run () : void
	{method} +toString () : String
}


interface demo.uml.classes.RunnableFuture {
	{method}  {abstract} +run () : void
}






@enduml