@startuml

scale 0.90
skinparam monochrome true
skinparam RectangleBackgroundColor white
skinparam StorageBackgroundColor white
skinparam NoteBackgroundColor white

rectangle "get the price\nin the EUR" as step4
rectangle "get the EUR/USD\nexchange rate" as step5

storage  "thenCombine" as step7
note right of step7: the net price\nin the USD

rectangle "get the tax" as step7b

storage  "thenCompose" as step8
note right of step8: the gross price\nin the USD

storage  "whenComplete" as step9

step4 --> step7
step5 --> step7

step7 --> step7b
step7 --> step8
step7b --> step8

step8 --> step9

@enduml
