@startuml

rectangle "Idle" as Idle
rectangle "Walk" as Walk
rectangle "Jump" as Jump
rectangle "Run" as Run

'[*] --> Idle
Idle --> Walk
Idle --> Run
Idle --> Jump
Walk --> Jump
Run --> Jump

'Walk --> [*]
'Run --> [*]
'Jump --> [*]

@enduml