@startuml
hide footbox
skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam titleFontSize 15
skinparam sequenceMessageAlign center

activate consumer
consumer->producer: submit task
activate producer
producer->producer: create promise
producer->>consumer: return future
Note right of producer: execute task
consumer->consumer: wait for\ntask completion
producer->producer: write promise
producer->consumer: complete future
deactivate producer
consumer->consumer: read future

||14||
producer -[#white]->]
@enduml