@startuml
hide footbox
skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam titleFontSize 15
skinparam sequenceMessageAlign center

activate consumer
consumer->producer: submit\ntask
activate producer
producer->>consumer: create promise\nreturn future
Note right of producer: execute task
consumer->consumer: wait for\ntask completion
Note right of producer: write promise
producer->consumer: complete future
deactivate producer
Note left of consumer: read future

||14||
producer -[#white]->]
@enduml