@startuml

together {
  interface java.util.concurrent.CompletionStage {}

  interface java.util.concurrent.Future {}
}

interface java.lang.Runnable {}

interface java.util.concurrent.RunnableFuture {}

together {
  class java.util.concurrent.FutureTask {}

  class java.util.concurrent.CompletableFuture {}
}

java.util.concurrent.CompletableFuture .up.|>  java.util.concurrent.CompletionStage
java.util.concurrent.CompletableFuture .up.|>  java.util.concurrent.Future
java.util.concurrent.FutureTask .up.|>  java.util.concurrent.RunnableFuture
java.util.concurrent.RunnableFuture .up.|>  java.util.concurrent.Future
java.util.concurrent.RunnableFuture .up.|>  java.lang.Runnable

hide members

@enduml