@startuml
scale 1.0
hide footbox
skinparam monochrome true
skinparam defaultFontName Source Sans Pro
skinparam titleFontSize 15
skinparam sequenceMessageAlign center

activate consumer
consumer->>producer: submit task
activate producer
producer->producer: create promise
producer->>consumer: return future
producer->producer: execute task
consumer->consumer: wait for\nfuture completion
producer->producer: write promise
producer->consumer: complete future
deactivate producer

||1||
producer -[#white]->]
@enduml