@startuml

!include header.iuml

class java.util.concurrent.FutureTask {
	{method} +cancel ( mayInterruptIfRunning : boolean ) : boolean
	{method} +get () : Object
	{method} +get ( timeout : long , unit : java.util.concurrent.TimeUnit ) : Object
	{method} +isDone () : boolean
	{method} +run () : void
	{method} +toString () : String
}

@enduml