@startuml

scale 0.9
skinparam monochrome true
skinparam RectangleBackgroundColor white

rectangle "Methods of the CompletionStage interface" as methods
rectangle "methods to\npipeline computations \n \n thenApply, thenCompose \n thenAccept \n thenRun \n \n applyToEither \n acceptEither \n runAfterEither \n \n thenCombine \n thenAcceptBoth \n runAfterBoth" as methods1
rectangle "methods to\nhandle exceptions \n \n whenComplete \n handle \n exceptionally \n exceptionallyCompose" as methods2

methods --> methods1
methods --> methods2

@enduml