@startuml

scale 1.0
skinparam monochrome true
skinparam RectangleBackgroundColor white

rectangle "Methods of the CompletionStage interface" as Methods
rectangle "methods to pipeline computations \n  \n thenApply, thenCompose \n thenAccept \n thenRun \n\n applyToEither \n acceptEither \n runAfterEither \n\n thenCombine \n thenAcceptBoth \n runAfterBoth" as Pipelining
rectangle "methods to handle exceptions \n  \n whenComplete \n handle \n exceptionally \n exceptionallyCompose" as ExceptionHandling

Methods --> ExceptionHandling
Methods --> Pipelining

@enduml