@startuml

scale 1.0
skinparam monochrome true
skinparam RectangleBackgroundColor white

rectangle "Methods of the CompletionStage interface" as Methods
rectangle "methods for pipelining \n  \n thenApply \n thenAccept \n thenRun" as Pipelining
rectangle "methods for exception handling \n  \n whenComplete \n handle \n exceptionally \n exceptionallyCompose" as ExceptionHandling

Methods --> ExceptionHandling
Methods --> Pipelining

@enduml