@startuml

scale 1.0
skinparam monochrome true
skinparam RectangleBackgroundColor white

rectangle "Methods of the CompletableFuture class" as Methods
rectangle "methods to create future \n  \n supplyAsync \n runAsync \n completedFuture \n failedFuture​" as MethodsToCreate
rectangle "methods to check status \n  \n isDone \n isCompletedExceptionally \n isCancelled" as MethodsToCheck
rectangle "methods for bulk operation \n  \n allOf \n anyOf" as MethodsForBulkOperation
rectangle "methods to complete future \n  \n complete \n completeOnTimeout \n orTimeout \n completeExceptionally \n cancel" as MethodsToComplete
rectangle "methods to get result \n  \n get \n join \n get(timeout, timeUnit) \n getNow(valueIfAbsent)" as MethodsToGet

Methods --> MethodsToCreate
Methods --> MethodsToCheck
Methods --[hidden]-> MethodsForBulkOperation
Methods --> MethodsToComplete
Methods --> MethodsToGet

@enduml