@startuml
scale 1.0

rectangle "get the first price\nin the GBP" as step1
rectangle "get the GBP/USD\nexchange rate" as step2
storage  "thenCombine" as step3
file "the first price\nin the USD" as step3a

rectangle "get the second\nprice in the EUR" as step4
rectangle "get the EUR/USD\nexchange rate" as step5
storage  "thenCombine" as step6
file "the second price\nin the USD" as step6a

storage  "thenCombine" as step7
file "the net price" as step7a
rectangle "get the tax formula" as step7b

storage  "thenCompose" as step8
file "the gross price" as step8a

storage  "whenComplete" as step9

step1 --> step3
step2 --> step3
step3 --> step3a

step4 --> step6
step5 --> step6
step6 --> step6a

step3a --> step7
step6a --> step7

step7 --> step7a
step7a --> step7b
step7a --> step8
step7b --> step8

step8 --> step8a
step8a --> step9

@enduml