@startuml

start
split
   -[hidden]->
split
   -[hidden]->
   :get the price in GBP;
split again
   -[hidden]->
   :get the GBP/USD\nexchange rate;
end split
:get the price in USD;
split again
   -[hidden]->
split
   -[hidden]->
   :get the price in EUR;
split again
   -[hidden]->
   :get the EUR/USD\nexchange rate;
end split
:get the price in USD;
end split
:get total price in USD;

:get tax;

:get total price in USD\nafter tax;
end

@enduml