@startuml

!include header.iuml

interface java.util.concurrent.Future {
	{method}  {abstract} +cancel ( mayInterruptIfRunning : boolean ) : boolean
	{method}  {abstract} +get () : Object
	{method}  {abstract} +get ( timeout : long , unit : java.util.concurrent.TimeUnit ) : Object
	{method}  {abstract} +isCancelled () : boolean
	{method}  {abstract} +isDone () : boolean
}

@enduml